version: "3.8"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mission
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      TZ: Asia/Tokyo
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/storage:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
